version: "3"

volumes:
  celery:
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
 django: &django
  build:
   context: ./
  volumes:
   - ./django_examples/:/app
   - ./toolbox_view/:/libraries/toolbox_view
   - /var/run/docker.sock:/var/run/docker.sock
   - celery:/celery
  command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8027"

  environment:
   - PYTHONPATH=/libraries
  ports:
   - 8027:8027
  depends_on:
    - redis

 redis:
   image: redis:5.0.7-alpine

 celery:
   <<: *django
   image: celeryworker
   command: celery -A django_examples worker -l info
   ports:
     - '5556'
   labels:
     - "none"
